<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jentibhai" ignored="0" name="Login Test" tests="2" failures="1" timestamp="2022-12-13T01:14:32 GMT" time="13.957" errors="0">
  <testcase name="userSholdLoginSuccessfullyWithValidCredentials" time="1.765" classname="com.hrmlive.testsuite.LoginPageTest"/>
  <testcase name="userShouldNavigateToForgotPasswordPageSuccessfully" time="1.128" classname="com.hrmlive.testsuite.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.hrmlive.testsuite.LoginPageTest.userShouldNavigateToForgotPasswordPageSuccessfully(LoginPageTest.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- userShouldNavigateToForgotPasswordPageSuccessfully -->
</testsuite> <!-- Login Test -->
